name: wiskuyy
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # --- Library Aplikasi ---
  provider: ^6.1.5+1
  shared_preferences: ^2.2.0
  http: ^1.1.0
  google_fonts: ^6.3.3
  cupertino_icons: ^1.0.8
  connectivity_plus: ^7.0.0
  supabase_flutter: ^2.12.0
  intl: ^0.20.2
  google_sign_in: ^6.2.1
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # Masukkan library icon generator di sini (karena cuma dipakai pas build)
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    

# --- KONFIGURASI ICON (Di Paling Bawah, Sejajar dengan flutter:) ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  # Pastikan file gambar ini BENAR-BENAR ADA di folder assets
  image_path: "assets/images/logo_aplikasi.png" 
  min_sdk_android: 21
  
  # Opsi agar icon bulat di Android tidak kotak putih
  adaptive_icon_background: "#ffffff"
  # Gunakan gambar yang sama atau khusus icon foreground
  adaptive_icon_foreground: "assets/images/logo_aplikasi.png"